export const properties = [
  {
    id: 1,
    title: "Rumah Type A Tulip",
    description: "Beautiful modern villa with ocean view",
    price: 25500,
    location: "Miami Beach",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    imageUrl: "/images/1.JPG",
    type: "house",
  },
  {
    id: 2,
    title: "Rumah Type B Mawar",
    description: "Perfect house for a growing family",
    price: 35000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/2.JPG",
    type: "house",
  },
  {
    id: 3,
    title: "Rumah Type 2 Mawar",
    description: "Perfect house for a growing family",
    price: 45000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/12.jpg",
    type: "house",
  },

  {
    id: 4,
    title: "Rumah Type 3 Tulip",
    description: "Perfect house for a growing family",
    price: 50000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/4.JPG",
    type: "house",
  },
  {
    id: 5,
    title: "Rumah Type 1 Anggrek",
    description: "Perfect house for a growing family",
    price: 35500,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/10.jpeg",
    type: "house",
  },
  {
    id: 6,
    title: "Rumah Type 3 Anggrek",
    description: "Perfect house for a growing family",
    price: 45200,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/6.jpg",
    type: "house",
  },
  {
    id: 7,
    title: "Rumah Type 1 Rafflesia",
    description: "Perfect house for a growing family",
    price: 45080,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/7.jpg",
    type: "house",
  },

  {
    id: 8,
    title: "Rumah Type 1 Lily",
    description: "Perfect house for a growing family",
    price: 45280,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/8.jpeg",
    type: "house",
  },
  {
    id: 9,
    title: "Rumah Type 3 Mawar",
    description: "Perfect house for a growing family",
    price: 45400,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/9.JPG",
    type: "house",
  },
  // Tambahkan properti lainnya
];
