export const properties = [
  {
    id: 1,
    title: "Rumah Type A Tulip",
    description: "Rumah yang berkarakter dan modern",
    price: 25500,
    location: "Bandar Lampung",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    imageUrl: "/images/1.JPG",
    type: "house",
  },
  {
    id: 2,
    title: "Rumah Type B Mawar",
    description: "Rumah yang cocok ditinggali oleh keluarga",
    price: 35000,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/2.JPG",
    type: "house",
  },
  {
    id: 3,
    title: "Rumah Type 2 Mawar",
    description: "Rumah yang nyaman untuk ditinggali",
    price: 45000,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/12.jpg",
    type: "house",
  },

  {
    id: 4,
    title: "Rumah Type 3 Tulip",
    description: "Masa Depan, Satu Rumah dalam Satu Waktu.",
    price: 50000,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/4.JPG",
    type: "house",
  },
  {
    id: 5,
    title: "Rumah Type 1 Anggrek",
    description: "Rumah Hangat untuk Masa Depan Cerah.",
    price: 35500,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/10.jpeg",
    type: "house",
  },
  {
    id: 6,
    title: "Rumah Type 3 Anggrek",
    description: "Rumah Idaman, Investasi Masa Depan.",
    price: 45200,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/6.jpg",
    type: "house",
  },
  {
    id: 7,
    title: "Rumah Type 1 Rafflesia",
    description: "Hunian Impian, Kenyamanan Sejati.",
    price: 45080,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/7.jpg",
    type: "house",
  },

  {
    id: 8,
    title: "Rumah Type 1 Lily",
    description: "Tempat Tinggal, Tempat Bahagia.",
    price: 45280,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/8.jpeg",
    type: "house",
  },
  {
    id: 9,
    title: "Rumah Type 3 Mawar",
    description: "Rumah yang Mengerti Anda.",
    price: 45400,
    location: "Bandar Lampung",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/9.JPG",
    type: "house",
  },
  // Tambahkan properti lainnya
];
