export const properties = [
  {
    id: 1,
    title: "Modern Villa",
    description: "Beautiful modern villa with ocean view",
    price: 1500000,
    location: "Miami Beach",
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    imageUrl: "/images/1.JPG",
    type: "house",
  },
  {
    id: 2,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/2.JPG",
    type: "house",
  },
  {
    id: 3,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/12.jpg",
    type: "house",
  },

  {
    id: 4,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/4.JPG",
    type: "house",
  },
  {
    id: 5,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/10.jpeg",
    type: "house",
  },
  {
    id: 6,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/6.jpg",
    type: "house",
  },
  {
    id: 7,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/7.jpg",
    type: "house",
  },

  {
    id: 8,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/8.jpeg",
    type: "house",
  },
  {
    id: 9,
    title: "Cozy Family House",
    description: "Perfect house for a growing family",
    price: 450000,
    location: "Suburbia",
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    imageUrl: "/images/9.JPG",
    type: "house",
  },
  // Tambahkan properti lainnya
];
